# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: true

common:
  storage:
    backend: s3
    s3:
      endpoint: "${s3_endpoint}"
      bucket_name: "${s3_bucket}"
      secret_access_key: "${s3_secret_access_key}"
      access_key_id: "${s3_access_key_id}"

blocks_storage:
  storage_prefix: blocks
  backend: s3

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 8080
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1

limits:
  ingestion_rate: 100000
  max_global_series_per_user: 15000000
